# Book settings
# Learn more at https://jupyterbook.org/customize/config.html

title: My sample book
author: The Jupyter Book Community
logo: logo.png

parse:
  myst_enable_extensions:
    - amsmath
    - colon_fence
    - deflist
    - dollarmath
    - html_admonition
    - html_image
    - linkify
    - replacements
    - smartquotes
    - substitution
    
only_build_toc_files: true

# Force re-execution of notebooks on each build.
# See https://jupyterbook.org/content/execute.html
execute:
  execute_notebooks: force
  timeout: 600    # The maximum time (in seconds) each notebook cell is allowed to run.

# Define the name of the latex output file for PDF builds
latex:
  latex_documents:
    targetname: book.tex

# Add a bibtex file so that we can create citations
bibtex_bibfiles:
  - references.bib

# Information about where the book exists on the web
repository:
  url: https://github.com/gewios/gdsjb  # Online location of your book
  branch: main  # Which branch of the repository should be used when creating links (optional)

# Add GitHub buttons to your book
# See https://jupyterbook.org/customize/config.html#add-a-link-to-your-repository
html:
  baseurl: https://gewios.github.io/gdsjb/
  use_issues_button: true
  use_repository_button: true
  use_edit_page_button: true

launch_buttons:
  notebook_interface: "jupyterlab"  # or "classic"
  binderhub_url: https://mybinder.org  # The URL of the BinderHub (e.g., https://mybinder.org)
  thebe: true
  
sphinx:
  config:
    html_theme_options:
      use_download_button: false
      repository_url: https://github.com/gewios/gdsjb
      use_issues_button: true
      use_repository_button: true
      use_edit_page_button: true
      launch_buttons: {
        binderhub_url: "https://mybinder.org",
        thebe: true
    }


